public with sharing class CheckPWD {
    public CheckPWD() {
        if (true) {
            if (true) {
                if (true) {
                    if (true) {
                        if (true) {
                            for(Integer i = 1; i<=100; i++){
                                Account a = [Select Id from Account];
                            }
                        }
                    }
                }
            }
        }

    }
}
